name: Release
on:
  push:
    branches:
      - rust-cli

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          # Macos
          - { os: macos-latest, target: x86_64-apple-darwin }
          # Windows
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
        target_cpu: [generic, broadwell]
        toolchain: [stable]
        cross: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile and release
        uses: Douile/rust-build.action@v0.1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
